### PR TITLE
Added support for parse_markdown_links

### PR DESCRIPTION
**Pull request by bryanjclark**
Now ADNKit can support inline markdown links.

### CODE REVIEW

**Comment by bryanjclark** [comment]
cc @berg

**Comment by berg** [comment]
This is already in my other (admittedly big) PR. Would love to get that whole thing merged, just would like someone else to look at those patches and make sure nothing seems off...

**Comment by bryanjclark** [comment]
Ah, yep! I see that now. :)

**Comment by berg** [comment]
Gonna close this 'cuz I merged that other PR.

**Pull request closed without merging**
