### PR TITLE
The project could not be compiled on iOS.

### PR DESCRIPTION
**Pull request by shpakovski**
Please investigate into this and merge the pull request or advise another solution. Thanks in advance!

### CODE REVIEW

**Comment by joeldev** [comment]
Looks like your header search path needs to be adjusted so it's both the Release folder itself and the specific headers directory you'd like to use. I have many iOS projects that build ADNKit as a subproject, and I know a few other developers who do as well.

**Comment by shpakovski** [comment]
Thank you for confirmation! I will investigate into this more.

**Comment by joeldev** [comment]
I will make more adjustments to the README so that this doesn't happen as much. If you look at the installation section it explains how it should be set up. Sorry for the confusion here!

**Comment by shpakovski** [comment]
OK, it looks like you should not call `git submodule update --init --recursive` when the project has already got some submodules. Now I removed all modules and added them back. Everything is ok! Sorry for bothering :)

**Comment by shpakovski** [comment]
Ugh… I finally cracked it. The project ADNKit won't compile if its path contains spaces. To fix this, you should change `$(SRCROOT)` to `"$(SRCROOT)"` in the Build Settings. Makes sense?

**Comment by joeldev** [comment]
Ah yep, that would do it

**Pull request closed without merging**
