### PR TITLE
API additions to support Ohai

### PR DESCRIPTION
**Pull request by stevestreza**
Ohai needed a few API additions to ADNKit, and they are included here.
- Support for filtering annotations by type on ANKAnnotatableResource
- Support for requesting machine-only posts on ANKClient
- Support for requesting files using specific read-only tokens
- Support for fetching subscribed ANKChannels, limited to specific types

I've tried to maintain the coding styles and patterns the project already uses, but I'm happy to make any changes desired.

### CODE REVIEW

**Comment by kolinkrewinkel** [comment]
Reviewed, looks good. Well done getting each feature into one commit! :+1:

**Comment by joeldev** [comment]
The only one of these I am not entirely sure about is the machine-only posts one. This feature already exists via the generalParameters object that each ANKClient has.

See: https://github.com/joeldev/ADNKit/blob/master/ADNKit/ANKGeneralParameters.h

**Comment by kolinkrewinkel** [comment]
By that logic, should the -includeAnnotations property be removed as well? That would move everything into ANKGeneralParameters. I was unsure of that one but let it slip because there was already duplicity with annotations.

**Comment by joeldev** [comment]
Yup, I would like to remove includeAnnotations as well. ANKGeneralParameters is the correct place to set that stuff.

**Pull request merged**
